# 1. 图像的特征

In [3]:
import cv2

img = cv2.imread("00016.png")
print(img.shape)

(720, 1280, 3)


## 1.1. 卷积

- $$h(x) = \int _{- \infty} ^{\infty} f(\tau) g(x - \tau) \mathrm{d} \tau$$

- 离散化

- $f(\tau)$是一个图像
    - $\tau \to (i, j)$是图像中像素的位置
    - $f(i, j)$就是像素（三通道）
    

- 离散$(i, j)$：
    - $f(i,j) \quad (i,j) \in [-1, 1]$
    - $f(i,j)$是$3 \times 3$矩阵

- $x \to (x, y)$

- 积分就是求和
    - $\int \to \sum$

- 离散的结果是：
    - $$ h(x, y) = \sum _{(i,j) \in [-1, 1]} f(i, j) g(x-i, y-j) $$

- filter2D
    - `dst=cv.filter2D(src, ddepth, kernel[, dst[, anchor[, delta[, borderType]]]])`

```python 
    dst = cv.filter2D(
        src,    # 原图像：g(x,y)
        ddepth,  # 输出的图像深度：通道，类型； -1表示深度相同
        kernel,  # 模板：f(i,j):卷积核
        dst,  #输出图像（不建议参数中返回）
        anchor, # kernel与原图像的参照点
        delta, # 偏移值，改变结果图像的灰度 
        borderType # 越界的替代值
    ) 

```

In [4]:
import cv2
import numpy
# 原图像
src = cv2.imread("00016.png")

# kernel
kernel = numpy.array([
    [-1,  0,  1],
    [-1,  0,  1],
    [-1,  0,  1]
])
# kernel = numpy.array([
#     [-1, -1, -1],
#     [ 0,  0,  0],
#     [ 1,  1,  1]
# ])
# kernel = numpy.array([
#     [-1, -1, -1],
#     [-1,  8, -1],
#     [-1, -1, -1]
# ])


# 卷积运算
dst = cv2.filter2D(src, -1, kernel, delta=128)

cv2.imwrite("dd.png", dst)

True

![输出图像](dd.png)

- 图像的导数 
    - $ f ^{\prime}(x) = \lim \limits _{\epsilon \to 0} \dfrac{f(x + \epsilon) - f(x - \epsilon)}{2 \epsilon}$

- $\epsilon = 1$

- $f ^ {\prime}(x, y) = \dfrac{1}{2}(f(x+1, y) + 0f(x, y) - f(x-1, y) )$

- $[f(x+1, y), f(x, y), f(x-1, y)] [1, 0,-1] $

# 高斯核

In [8]:
import cv2
import numpy as np

kernel_gauss = cv2. getGaussianKernel(ksize=3, sigma=1)
kernel = np.hstack((kernel_gauss, kernel_gauss, kernel_gauss))
print(kernel)

# 原图像
src = cv2.imread("00016.png")# 卷积运算
dst = cv2.filter2D(src, -1, kernel, delta=-50)

cv2.imwrite("gaoSi.png", dst)

[[0.27406862 0.27406862 0.27406862]
 [0.45186276 0.45186276 0.45186276]
 [0.27406862 0.27406862 0.27406862]]


True

![输出图片](gaoSi.png)

- 高斯kernel
- Sobel核
- Laplace核

- $\texttt{dst} = \frac{\partial^{xorder+yorder} \texttt{src}}{\partial x^{xorder} \partial y^{yorder}}$